version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - BOT_SERVICE_URL=http://bot:8001
    volumes:
      - ./api:/app
    restart: always

  bot:
    build: ./bot
    depends_on:
      api:
        condition: service_started
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - API_URL=http://api:8000
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - PAYMENT_PROVIDER_TOKEN=${PAYMENT_PROVIDER_TOKEN}
    volumes:
      - ./bot:/app
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - bot
    restart: always

volumes:
  postgres_data: