version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"  # Optional: expose for debugging

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database configuration that matches database.py
      - PG_USER=${DB_USER}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_DATABASE=${DB_NAME}
      - PG_HOST=db
      - PG_PORT=5432
      # Bybit API configuration
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - BYBIT_TESTNET=${BYBIT_TESTNET}
      # Bot service URL
      - BOT_SERVICE_URL=http://bot:8001
    volumes:
      - ./api:/app
    restart: always
#    ports:
#      - "8000:8000"  # Optional: expose for debugging

  bot:
    build: ./bot
    depends_on:
      api:
        condition: service_started
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - API_URL=http://api:8000
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - PAYMENT_PROVIDER_TOKEN=${PAYMENT_PROVIDER_TOKEN}
    volumes:
      - ./bot:/app
    restart: always
#    ports:
#      - "8001:8001"  # Optional: expose for debugging

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - bot
    restart: always

volumes:
  postgres_data: